### ISSUE TITLE
Messaging - relocate "choose address from address book" button

### ISSUE THREAD

**Issue by rubber-duckie-au** [CryptoCoderz/DigitalNote#23]
Move choose address from address book button next to Send To Textbox. As the button populates all three fields, best to have it on the first line

![image](https://user-images.githubusercontent.com/53319864/89635537-7976d800-d8ea-11ea-9480-e6d336f313bd.png)

**Comment by CryptoCoderz** [comment]
Thanks bud will get to work on it
