### ISSUE TITLE
Debug Window popup on Address book Send To selection

### ISSUE THREAD

**Issue by rubber-duckie-au** [CryptoCoderz/DigitalNote#26]
Select the address book and select an address to send to and get a debug popup with the address on it...

![image](https://user-images.githubusercontent.com/53319864/89969391-9bc97680-dc99-11ea-9fb5-4cd7f4c0a454.png)

**Comment by CryptoCoderz** [comment]
Thank you! Multi address handling is to blame here, we'll adapt the address book to handle this asap.
