### ISSUE TITLE
QT: Show info message when wallet is locked in the list of conversations

### ISSUE THREAD

**Issue by vgulkevic** [CryptoCoderz/DigitalNote#35]
Something like 'Unlock wallet to see conversations'

**Comment by CryptoCoderz** [comment]
Will be added in v1.0.3.3

**Comment by CryptoCoderz** [comment]
resolved in: https://github.com/CryptoCoderz/DigitalNote/commit/94adbb86757f017df4d472a8393ae6a89b333f14
