### ISSUE TITLE
Not enough conversion specifiers in format string

### ISSUE THREAD

**Issue by g1itch** [CryptoCoderz/DigitalNote#4]
Hello!

I added `debug=1` into digitalnote's config file and probably found a bug here:
https://github.com/CryptoCoderz/DigitalNote/blob/master/src/blockparams.cpp#L104

**Comment by CryptoCoderz** [comment]
Thank you so much for pointing this out! I have two values there and only one called so this is the issue. I'll take care of this right away!

**Comment by CryptoCoderz** [comment]
This issue has been corrected as of commit: https://github.com/CryptoCoderz/DigitalNote/commit/c57db922bf8821b4c265f34188dab22f8dc113f3

Thank you once more!
